controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_hello_world:
    path: /helloworld
    controller: App\Controller\HelloController::hello